### ISSUE TITLE
Conversion of dynamic social layered costmap to other mobile platform

### ISSUE THREAD

**Issue by Megacephalo** [marinaKollmitz/human_aware_navigation#1]
Hi Marina,

First of all, thank you for your package for human_aware_navigation, it helps me a lot in understanding how social costmap collaborates with the Navigation Stack. However, if I wish to adapt your dynamic social costmap plugin to any other platform, what can I do? I wrote my <code>common_params.yaml</code> for move_base as below:

```
robot_base_frame: base_link

# obstacle_range: 6.0
# raytrace_range: 6.5

max_obstacle_height: 2.0
min_obstacle_height: -1.0

use_dijkstra: false
# visualize_potential: false



footprint: [[0.50, 0.50], [0.50, -0.50], [-0.50, -0.50], [-0.50, 0.50] ]  

# NOTE!! that including obstacles it may happen that in narrow corridors echos from the laser scanner may appear as obstacles!
# Not needed anyway cause using the static map layer
obstacles:
     observation_sources: scan 
     scan: 
       data_type: LaserScan
       topic: /beebot/laser/scan
       sensor_frame: /hokuyo_link 
       marking: true 
       clearing: true 
     obstacle_range: 30.0
     raytrace_range: 30.0
     enabled: true

inflater:   
     observation_sources: scan 
     scan: 
    data_type: LaserScan
    topic: /beebot/laser/scan 
    sensor_frame: /hokuyo_link 
    marking: true 
    clearing: true 
    map_type: costmap
     inflation_radius: 1.2
     enabled: true

dynamic_social_costmap:
     observation_sources: people 
     people: 
    data_type: people_msgs/People
    topic: /people  
    marking: true 
    clearing: true 
    map_type: costmap
     inflation_radius: 1.2
     enabled: true
```

For dynamic_social_costmap, I deduced from the source code that the local costmap node should subscribe to /people topic, so I put it this way. Once dynamic_social_costmap is announced, I hence announce the usage of this layer costmap in <code>global_costmap.yaml</code> and <code>local_costmap.yaml</code>. However, I must have missed something because move_base does not initialize as with other layered costmap. 
I saw you loaded the costmap plugin as:
`<param name="TBPlanner/dynamic_layers_plugin" value="dynamic_social_costmap::SocialLayers" />`
into move_base. Thus, what should be the correct way of loading the social costmap in any other yaml file? Thank you so much !

**Comment by marinaKollmitz** [comment]
Hi Megacephalo, 

I am glad you find my code useful. But I think there might be some confusion here. The dynamic_social_costmap is a plugin for the [lattice_planner](https://github.com/marinaKollmitz/lattice_planner), which is a time dependent global planner for the ROS navigation stack. The dynamic_social_costmap has multiple layers, each one representing the costs at one particular time step in the future. The ROS costmap_2d also uses a layered representation, but the layers represent different sources of costs and are all static. In fact, the static ROS costmap is used as a static layer in the dynamic_social_costmap package. Unfortunately, the dynamic_social_costmap plugin cannot be used directly inside the raw navigation stack, because it is not intended for time dependent planning. But you can use it in combination with the [lattice_planner](https://github.com/marinaKollmitz/lattice_planner).

I hope I understand your question and could answer it properly.
Best,

Marina

**Comment by marinaKollmitz** [comment]
If you are interested in a static costmap plugin for social cost representation, you can have a look at David Lu!!'s [social_navigation_layers](http://wiki.ros.org/social_navigation_layers).

**Comment by Megacephalo** [comment]
Hi Marina, 
This is the first time I've ever learned there could be one plugin in another. Well, at this point, I also took a look on the social_compliance layer costmap offered by Social Robotic Lab at Freiburg. I am not sure if they are using dynamic or static map for the social costmap but if everything could apply to create any social map, I totally appreciate for the help. 
Anyway, thank you for clarifying my doubt! I understand now. :)
